import { Character } from "@/types/game";

export const INITIAL_CHARACTERS: Record<string, Character> = {
  chancellor_vane: {
    id: "chancellor_vane",
    name: "Lorde Vane",
    title: "Chanceler da Coroa",
    role: "Chanceler",
    loyalty: 35,
    influence: 75,
    alive: true,
    traits: ["Astuto", "Aristocrata", "Ambicioso"],
    faction: "nobles",
    avatar: "👑",
  },
  general_thorne: {
    id: "general_thorne",
    name: "General Thorne",
    title: "Comandante das Legiões",
    role: "General",
    loyalty: 60,
    influence: 80,
    alive: true,
    traits: ["Disciplinado", "Veterano", "Implacável"],
    faction: "military",
    avatar: "⚔️",
  },
  merchant_alistair: {
    id: "merchant_alistair",
    name: "Mestre Alistair",
    title: "Porta-voz da Liga Mercante",
    role: "Comerciante",
    loyalty: 40,
    influence: 70,
    alive: true,
    traits: ["Pragmático", "Rico", "Calculista"],
    faction: "merchants",
    avatar: "💰",
  },
  archbishop_ignatius: {
    id: "archbishop_ignatius",
    name: "Arcebispo Ignatius",
    title: "Guardião da Chama Sagrada",
    role: "Sacerdote",
    loyalty: 50,
    influence: 65,
    alive: true,
    traits: ["Piedoso", "Dogmático", "Tradicionalista"],
    faction: "clergy",
    avatar: "🕊️",
  },
  elenor_peasant: {
    id: "elenor_peasant",
    name: "Elenor dos Vales",
    title: "Voz dos Lavradores",
    role: "Camponesa",
    loyalty: 20,
    influence: 45,
    alive: true,
    traits: ["Obstinada", "Carismática", "Idealista"],
    faction: "peasants",
    avatar: "🌾",
  },
};
