import { Realm } from "@/types/game";

export type ExternalEntity = Realm & {
  type: "kingdom" | "empire" | "horde" | "city-state" | "station" | "corp" | "faction";
  leader?: string;
  leaderTitle?: string;
  ideology?: string;
  capital?: string;
  territory?: string;
  militaryStrength?: "negligível" | "fraco" | "moderado" | "forte" | "esmagador";
  economicPower?: "pobre" | "modesto" | "próspero" | "rico" | "dominante";
  atWar?: boolean;
  warReason?: string;
  recentAction?: string;
  border?: boolean;
  distance?: "vizinho" | "próximo" | "distante" | "ultramar";
  color?: string; // for map rendering
};

export const INITIAL_REALMS: Record<string, Realm> = {
  arvandor: {
    id: "arvandor",
    name: "Império de Arvandor",
    population: 45000,
    military: 85,
    wealth: 70,
    relation: -15,
    flags: { militarist: true },
  },
  eldoria: {
    id: "eldoria",
    name: "Principado de Eldoria",
    population: 28000,
    military: 45,
    wealth: 95,
    relation: 30,
    flags: { trade_hub: true },
  },
  khar: {
    id: "khar",
    name: "Horda de Khar",
    population: 32000,
    military: 75,
    wealth: 30,
    relation: -40,
    flags: { raiders: true },
  },
};

// Entidades externas ricas por storyline — usadas no mapa e na diplomacia
export const EXTERNAL_ENTITIES: Record<string, ExternalEntity[]> = {
  valoria_classic: [
    {
      id: "arvandor",
      name: "Império de Arvandor",
      type: "empire",
      leader: "Imperador Mael III",
      leaderTitle: "Imperador da Sanha",
      ideology: "Expansionismo Militarista",
      capital: "Cidade de Arx Magna",
      territory: "Leste Continental",
      militaryStrength: "esmagador",
      economicPower: "rico",
      population: 45000,
      military: 85,
      wealth: 70,
      relation: -15,
      atWar: false,
      warReason: undefined,
      recentAction: "Enviou embaixadores exigindo tributo do trigo colhido em Oakhaven",
      border: true,
      distance: "vizinho",
      flags: { militarist: true },
      color: "#3f2020",
    },
    {
      id: "eldoria",
      name: "Principado de Eldoria",
      type: "city-state",
      leader: "Príncipe Rowan de Eldoria",
      leaderTitle: "Senhor dos Portos",
      ideology: "Mercantilismo Pacífico",
      capital: "Porto de Eldrith",
      territory: "Arquipélago do Sul",
      militaryStrength: "fraco",
      economicPower: "dominante",
      population: 28000,
      military: 45,
      wealth: 95,
      relation: 30,
      atWar: false,
      recentAction: "Propôs tratado de livre passagem marítima pela Costa das Mercadorias",
      border: false,
      distance: "próximo",
      flags: { trade_hub: true },
      color: "#1a2f1a",
    },
    {
      id: "khar",
      name: "Horda de Khar",
      type: "horde",
      leader: "Khan Vorgath",
      leaderTitle: "Senhor das Estepes",
      ideology: "Pilhagem e Expansão Tribal",
      capital: "Acampamento Móvel (Malkhor)",
      territory: "Estepes do Norte",
      militaryStrength: "forte",
      economicPower: "pobre",
      population: 32000,
      military: 75,
      wealth: 30,
      relation: -40,
      atWar: false,
      recentAction: "Atacou caravanas do Passo da Fronteira Leste com cavalaria de vanguarda",
      border: true,
      distance: "vizinho",
      flags: { raiders: true },
      color: "#2a1a00",
    },
    {
      id: "igreja_sagrada",
      name: "Sé Papal de Avalon",
      type: "faction",
      leader: "Sumo Pontífice Benedictus V",
      leaderTitle: "Vigário da Chama",
      ideology: "Teocracia e Influência Moral",
      capital: "Avalon Santa",
      territory: "Enclave Neutro",
      militaryStrength: "negligível",
      economicPower: "próspero",
      population: 8000,
      military: 10,
      wealth: 80,
      relation: 20,
      atWar: false,
      recentAction: "Ameaçou excomungar qualquer rei que taxe os celeiros do clero",
      border: false,
      distance: "próximo",
      flags: { religious: true },
      color: "#1a1a2f",
    },
  ],

  khar_invasion: [
    {
      id: "khar_vanguarda",
      name: "Horda Vanguarda de Khar",
      type: "horde",
      leader: "Khan Vorgath",
      leaderTitle: "Conquistador das Estepes",
      ideology: "Conquista Total e Genocídio Cultural",
      capital: "Acampamento Sitiante (Malkhor)",
      territory: "Norte em Avanço",
      militaryStrength: "esmagador",
      economicPower: "pobre",
      population: 50000,
      military: 92,
      wealth: 25,
      relation: -90,
      atWar: true,
      warReason: "Invasão total — o Khan jurou raspar os muros da Cidadela",
      recentAction: "Cercou três fortalezas e lançou catapultas incendiárias ao anoitecer",
      border: true,
      distance: "vizinho",
      flags: { raiders: true, sieging: true },
      color: "#3a1000",
    },
    {
      id: "eldoria_exilada",
      name: "Eldoria (Refugiada)",
      type: "kingdom",
      leader: "Príncipe Rowan de Eldoria",
      leaderTitle: "Líder em Exílio",
      ideology: "Sobrevivência e Pacifismo Pragmático",
      capital: "Acampamento nos Montes Cinzentos",
      territory: "Montes Cinzentos",
      militaryStrength: "negligível",
      economicPower: "pobre",
      population: 8000,
      military: 12,
      wealth: 20,
      relation: 55,
      atWar: false,
      recentAction: "Pediu asilo militar e acesso às rotas de suprimento meridionais",
      border: true,
      distance: "vizinho",
      flags: { refugee: true },
      color: "#1a2a1a",
    },
    {
      id: "arvandor_neutro",
      name: "Império de Arvandor",
      type: "empire",
      leader: "Imperador Mael III",
      leaderTitle: "Imperador da Sanha",
      ideology: "Oportunismo Estratégico",
      capital: "Arx Magna",
      territory: "Leste Continental",
      militaryStrength: "esmagador",
      economicPower: "rico",
      population: 45000,
      military: 85,
      wealth: 70,
      relation: -5,
      atWar: false,
      recentAction: "Observa o colapso e negocia termos de proteção caso o bastião caia",
      border: false,
      distance: "distante",
      flags: { opportunist: true },
      color: "#3f2020",
    },
  ],

  dark_plague: [
    {
      id: "sé_inquisição",
      name: "Santa Inquisição de Avalon",
      type: "faction",
      leader: "Grande Inquisidor Cassius",
      leaderTitle: "Punho da Chama",
      ideology: "Purificação pelo Fogo — morte ao contaminado",
      capital: "Avalon Santa",
      territory: "Enclave Eclesiástico",
      militaryStrength: "moderado",
      economicPower: "próspero",
      population: 12000,
      military: 55,
      wealth: 75,
      relation: -20,
      atWar: false,
      warReason: undefined,
      recentAction: "Enviou pelotões de purificação para queimar bairros inteiros 'infestados'",
      border: false,
      distance: "próximo",
      flags: { fanatical: true },
      color: "#2a001a",
    },
    {
      id: "boticarios_livres",
      name: "Liga dos Boticários Livres",
      type: "faction",
      leader: "Mestra Isolde",
      leaderTitle: "Guardiã do Conhecimento",
      ideology: "Ciência Empírica contra o Misticismo",
      capital: "Lazareto das Ilhas",
      territory: "Ilhas Costeiras",
      militaryStrength: "negligível",
      economicPower: "modesto",
      population: 3000,
      military: 5,
      wealth: 45,
      relation: 50,
      atWar: false,
      recentAction: "Descobriu protocolo de quarentena que reduz a propagação em 60%",
      border: false,
      distance: "próximo",
      flags: { healer: true },
      color: "#001a1a",
    },
    {
      id: "arvandor_bloqueio",
      name: "Império de Arvandor",
      type: "empire",
      leader: "Imperador Mael III",
      leaderTitle: "Imperador Sanitário",
      ideology: "Bloqueio Sanitário Total",
      capital: "Arx Magna",
      territory: "Leste Continental",
      militaryStrength: "esmagador",
      economicPower: "rico",
      population: 45000,
      military: 85,
      wealth: 70,
      relation: -35,
      atWar: false,
      recentAction: "Declarou embargo total: nenhum navio de Valoria pode aportar em suas costas",
      border: true,
      distance: "vizinho",
      flags: { embargo: true },
      color: "#3f2020",
    },
  ],

  colony_exodus: [
    {
      id: "corp_helios",
      name: "Corporação Hélios Prime",
      type: "corp",
      leader: "CEO Dax Vanthor",
      leaderTitle: "Diretor Executivo Vitalício",
      ideology: "Lucro sobre Vida — Colonização Exploratória",
      capital: "Sede Central (Órbita Terra)",
      territory: "Sistema Solar Interno",
      militaryStrength: "forte",
      economicPower: "dominante",
      population: 0,
      military: 78,
      wealth: 98,
      relation: -50,
      atWar: false,
      recentAction: "Exigiu devolução da estação como propriedade corporativa — com prazo de 90 ciclos",
      border: false,
      distance: "distante",
      flags: { corporate: true },
      color: "#2a1a2a",
    },
    {
      id: "federacao_livre",
      name: "Federação dos Mundos Livres",
      type: "faction",
      leader: "Almirante Yara Osei",
      leaderTitle: "Comandante da Frota",
      ideology: "Democracia Espacial — Autodeterminação",
      capital: "Estação Liberdade (Cinturão)",
      territory: "Cinturão de Asteroides",
      militaryStrength: "moderado",
      economicPower: "modesto",
      population: 15000,
      military: 60,
      wealth: 40,
      relation: 45,
      atWar: false,
      recentAction: "Enviou fregata de apoio com suprimentos médicos e módulos de reparação",
      border: false,
      distance: "próximo",
      flags: { ally_candidate: true },
      color: "#001a2a",
    },
    {
      id: "piratas_vazio",
      name: "Coalizão do Vazio",
      type: "horde",
      leader: "Capitã Sable",
      leaderTitle: "Rainha do Vácuo",
      ideology: "Anarquismo Espacial — Pilhagem de Recursos",
      capital: "Sucata X-91 (Setor Escombros)",
      territory: "Zona de Exclusão",
      militaryStrength: "moderado",
      economicPower: "pobre",
      population: 5000,
      military: 50,
      wealth: 30,
      relation: -65,
      atWar: true,
      warReason: "Atacaram os painéis solares e interceptaram a última carga de hélio-3",
      recentAction: "Mais dois módulos externos foram desacoplados por drones de pilhagem",
      border: true,
      distance: "vizinho",
      flags: { pirates: true },
      color: "#1a1000",
    },
  ],
  zombie_apocalypse: [
    {
      id: "horda_leste",
      name: "A Grande Horda do Leste",
      type: "horde",
      leader: "Alfa Primário",
      leaderTitle: "Vetor Primário Mutante",
      ideology: "Assimilacionismo Biológico Total",
      capital: "Metrópole em Ruínas (Setor Zero)",
      territory: "Planícies Orientais Contaminadas",
      militaryStrength: "esmagador",
      economicPower: "pobre",
      population: 50000,
      military: 90,
      wealth: 0,
      relation: -90,
      atWar: true,
      warReason: "Horda avança consumindo toda biomassa viva em direção às muralhas do Bastião",
      recentAction: "A vanguarda destruiu as primeiras cercas eletrificadas do anel externo",
      border: true,
      distance: "vizinho",
      flags: { undead: true },
      color: "#2a0505",
    },
    {
      id: "faccao_escarlate",
      name: "Culto dos Filhos da Praga",
      type: "faction",
      leader: "Profeta Elias Sangue-Puro",
      leaderTitle: "Guia da Ascensão Biológica",
      ideology: "Fanatismo Apocalíptico — Imunidade pela Infecção",
      capital: "Catedral Subterrânea do Metrô",
      territory: "Túneis e Galerias do Sul",
      militaryStrength: "moderado",
      economicPower: "modesto",
      population: 3000,
      military: 55,
      wealth: 40,
      relation: -45,
      atWar: false,
      recentAction: "Espalharam panfletos clandestinos incitando sabotagem dos geradores de energia",
      border: true,
      distance: "próximo",
      flags: { hostile: true },
      color: "#3a1515",
    },
    {
      id: "bunkers_cooperados",
      name: "Aliança de Bunkers de Ferro",
      type: "city-state",
      leader: "Superintendente Teresa Silva",
      leaderTitle: "Superintendente da Rede Subterrânea",
      ideology: "Tecnocracia Cooperativa de Sobrevivência",
      capital: "Complexo Hidroelétrico Sul",
      territory: "Cordilheira dos Silos",
      militaryStrength: "fraco",
      economicPower: "rico",
      population: 5500,
      military: 30,
      wealth: 75,
      relation: 35,
      atWar: false,
      recentAction: "Propuseram comboio blindado para trocar filtros de purificação por munições",
      border: false,
      distance: "próximo",
      flags: { trade_partner: true },
      color: "#152515",
    },
    {
      id: "bandoleiros",
      name: "Bandoleiros das Autopistas",
      type: "horde",
      leader: "Comandante 'Cão de Caça' Barreto",
      leaderTitle: "Senhor dos Veículos Blindados",
      ideology: "Lei do Mais Forte — Pilhagem de Convois",
      capital: "Refinaria Abandonada da Autopista 9",
      territory: "Pistas e Ruínas Ocidentais",
      militaryStrength: "moderado",
      economicPower: "pobre",
      population: 1200,
      military: 50,
      wealth: 35,
      relation: -60,
      atWar: false,
      recentAction: "Interceptaram o último caminhão-tanque de diesel destinado aos geradores do Bastião",
      border: true,
      distance: "vizinho",
      flags: { raiders: true },
      color: "#251a05",
    },
  ],
  rio_zombie: [
    {
      id: "milicia_linha_vermelha",
      name: "Milícia Blindada da Linha Vermelha",
      type: "horde",
      leader: "Major Carcará",
      leaderTitle: "Chefe dos Blindados do Asfalto",
      ideology: "Extorsão Armada e Bloqueio Rodoviário",
      capital: "Viadutos do Caju",
      territory: "Entrada Norte e Pistas da Linha Vermelha",
      militaryStrength: "forte",
      economicPower: "rico",
      population: 1800,
      military: 70,
      wealth: 65,
      relation: -50,
      atWar: false,
      recentAction: "Instalou ninhos de metralhadora .50 e ameaçou bombardear as traineiras de pesca",
      border: true,
      distance: "vizinho",
      flags: { hostile: true },
      color: "#4a1818",
    },
    {
      id: "ninho_estaladores_tijuca",
      name: "Ninho dos Estaladores da Tijuca",
      type: "faction",
      leader: "Estalador Alfa (Espécime 4)",
      leaderTitle: "Vetor Primário da Florada",
      ideology: "Infecção Fúngica Territorial",
      capital: "Penhascos do Corcovado",
      territory: "Mata Atlântica da Tijuca e Paineiras",
      militaryStrength: "esmagador",
      economicPower: "pobre",
      population: 4500,
      military: 90,
      wealth: 10,
      relation: -90,
      atWar: false,
      recentAction: "Liberou nuvens de esporos amarelos nas encostas que dessem em direção à enseada",
      border: true,
      distance: "vizinho",
      flags: { hostile: true },
      color: "#2d3810",
    },
    {
      id: "pescadores_paqueta",
      name: "República Livre de Paquetá",
      type: "city-state",
      leader: "Mestre Onofre",
      leaderTitle: "Decano dos Pescadores Insulares",
      ideology: "Comunitarismo e Autonomia Náutica",
      capital: "Balsa Principal de Paquetá",
      territory: "Ilha de Paquetá e Enseadas da Baía",
      militaryStrength: "fraco",
      economicPower: "próspero",
      population: 2100,
      military: 25,
      wealth: 75,
      relation: 40,
      atWar: false,
      recentAction: "Enviou traineira carregada de sal e peixe seco propondo permuta por munição 7.62",
      border: false,
      distance: "próximo",
      flags: { trade_partner: true },
      color: "#16332b",
    },
    {
      id: "forte_copacabana",
      name: "Guarnição do Forte de Copacabana",
      type: "empire",
      leader: "Coronel Silveira",
      leaderTitle: "Comandante da Bateria de 305mm",
      ideology: "Isolacionismo Militar e Mão de Ferro",
      capital: "Cúpula Blindada do Forte",
      territory: "Ponta de Copacabana e Orla Sul",
      militaryStrength: "esmagador",
      economicPower: "modesto",
      population: 600,
      military: 85,
      wealth: 50,
      relation: -10,
      atWar: false,
      recentAction: "Disparou tiros de advertência contra qualquer embarcação sem código de holofote",
      border: false,
      distance: "próximo",
      flags: { militarist: true },
      color: "#1c2438",
    },
  ],
};

export function getEntitiesForStoryline(storylineId: string): ExternalEntity[] {
  return EXTERNAL_ENTITIES[storylineId] || EXTERNAL_ENTITIES["valoria_classic"];
}
